name: Build and Test

on:
  push:
    branches:
      - master
      - Dev
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6  # Specify the .NET Core version you need

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test
