name: Build and Test

on:
  push:
    branches:
      - master
      - GH-Management
      - Dev
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Secreate
      run: echo ${{ secrets.NUGET_API_KEY }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: pwd && dotnet build --configuration Release

    - name: Test
      run: dotnet test
    
